### ISSUE TITLE
_expire in SessionData is never set to the value passed when the initial call to sessionPlugin

### ISSUE THREAD

**Issue by macnak** [gaurishhs/elysia-session#1]
Been looking at this code and found the _expiry is not being set to the value passed when the sessionPlugin function is called, in the options expireAfter:

My code using the sessionPlugin:

const app = new Elysia()
  .use(sessionPlugin({
    cookieName: "session", // Optional
    store: mongoStore,
    expireAfter: 15 * 60, // 15 minutes
  })).get("/", () => 'Hi').listen(3010);

I added the following code on my local copy to bring this value in, example below (The idea is to use the long ms time value and save as string this will make it easy to work out if it has expired - ):

        if (createRequired) {
            const expire = options.expireAfter === null ? null : new Date(Date.now() + options.expireAfter * 1000);
            const initialData: SessionData = {
                _data: {},
                _expire: expire === null ? null : expire.toString(),
                _delete: false,
                _accessed: null
            }
            sid = nanoid(24)
            store.createSession(initialData, sid, ctx)
            session.setCache(initialData)
        }

This was part of work to build a MongooseStore to leverage off this work which I have the create step working and I'm will to share the code updates to get this piece working as it is very close to being complete.

**Comment by gaurishhs** [comment]
`_expire` is managed by Session. You might want to look [here](https://github.com/gaurishhs/elysia-session/blob/main/src/session.ts#L32)

**Comment by macnak** [comment]
I understand, yet when I log the code it is not getting set and pushed to the store. It was always null, even when I set a value. And when using the Mogoose Store I did it was null there in the SessionData object passed.

**Comment by gaurishhs** [comment]
It must be managed by the store. Consider looking at the MemoryStore implementation. Also, I have added your store example to the readme [here](https://github.com/gaurishhs/elysia-session#community-stores)

**Comment by macnak** [comment]
You have a line of code:

        const session = new Session;         (line 18 - should that not be new Session())

**Comment by gaurishhs** [comment]
That shouldn't have an impact. You're correct i should have included parenthesis but it wouldn't change how that works because the constructor doesn't really take any arguments

**Comment by macnak** [comment]
My point is that on the session there is no call to "setExpire()" or check for it. So the value is null, and it is not set in the initialdata part when you call setCache(initialData: SessionData). This is my point, that it never gets set if you provide a value to "expireAfter".

**Comment by gaurishhs** [comment]
It does https://github.com/gaurishhs/elysia-session/blob/main/src/index.ts#L36

**Comment by macnak** [comment]
Okay, I have tested this out and had to fix my MongooseStore to use async. Then all good with the expiry. There were a few things I needed to change to get the index.ts side working:

https://github.com/gaurishhs/elysia-session/blob/main/src/index.ts#L25
add the line:
sid = cookie.value;  --> this will stop the cookie having an empty value when you have a valid session cookie
https://github.com/gaurishhs/elysia-session/blob/main/src/index.ts#L62


https://github.com/gaurishhs/elysia-session/blob/main/src/index.ts#L27
sessionData = await store.getSession(undefined, ctx)  --> change the undefined to sid that was set earlier


https://github.com/gaurishhs/elysia-session/blob/main/src/index.ts#L28
store.deleteSession(undefined, ctx) -->the same issue as line 27 and this stops leaks in the store (well as much as you can - I have ideas around that and not something your project needs to handle. I think that is a store implementation issue).


I tested this a bit with JMeter and doing 3+ requests per workflow to verify the cookie was being processed correctly. That is when I made the above changes and everything worked well.

You were right on the expiry stuff and it works a charm. What you built here was really nice and clean. Appreciate the work and answering my issues.

Once I clean up the Mongoose store I'll send another copy for you that works if you would like - I had bugs that did not come up till I load tested this.

**Comment by gaurishhs** [comment]
Thanks! Great to know it works for you. Make sure to open a PR when you do update.
